
server {
    include mime.types;
    listen 8080;

    location /static/ {
        alias /home/sager/Desktop/scrape_api/scrape/scrape/staticfiles/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
    }

    location  /favicon.ico { 
        access_log off; 
        log_not_found off;
    }

}